import type { Metadata } from "next"
import VideoPageClient from "./VideoPageClient"

export const metadata: Metadata = {
  title: "Video Tutorials",
  description: "Learn programming with curated video tutorials from top instructors",
}

interface Props {
  params: {
    language: string
  }
}

export default function VideoPage({ params }: Props) {
  const { language } = params

  // Video data with actual YouTube thumbnails
  const videoData = {
    javascript: [
      {
        title: "JavaScript Crash Course For Beginners",
        channel: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/hdI2bqOjy3c/maxresdefault.jpg",
        duration: "1h 40m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=hdI2bqOjy3c",
        description: "Learn JavaScript in one video with this crash course for beginners",
        tags: ["JavaScript", "Web Development", "Frontend"],
      },
      {
        title: "JavaScript Tutorial for Beginners: Learn JavaScript in 1 Hour",
        channel: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/W6NZfCO5SIk/maxresdefault.jpg",
        duration: "48m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=W6NZfCO5SIk",
        description: "JavaScript tutorial for beginners with all the basics you need to get started",
        tags: ["JavaScript", "Basics", "Tutorial"],
      },
      {
        title: "Learn JavaScript - Full Course for Beginners",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/PkZNo7MFNFg/maxresdefault.jpg",
        duration: "3h 26m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        description: "This complete JavaScript course will teach you everything you need to know",
        tags: ["JavaScript", "Full Course", "Comprehensive"],
      },
      {
        title: "JavaScript DOM Manipulation – Full Course for Beginners",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/5fb2aPlgoys/maxresdefault.jpg",
        duration: "7h 52m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=5fb2aPlgoys",
        description: "Learn how to manipulate the DOM using JavaScript in this full course for beginners",
        tags: ["JavaScript", "DOM", "Web Development"],
      },
      {
        title: "JavaScript ES6 Tutorial - Complete Crash Course",
        channel: "Dev Ed",
        thumbnail: "https://i.ytimg.com/vi/WZQc7RUAg18/maxresdefault.jpg",
        duration: "1h 13m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=WZQc7RUAg18",
        description: "Learn all the new features in ES6 JavaScript in this complete tutorial",
        tags: ["JavaScript", "ES6", "Modern JS"],
      },
      {
        title: "Async JS Crash Course - Callbacks, Promises, Async Await",
        channel: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/PoRJizFvM7s/maxresdefault.jpg",
        duration: "26m",
        level: "Advanced",
        url: "https://www.youtube.com/watch?v=PoRJizFvM7s",
        description: "Learn about asynchronous JavaScript features including callbacks, promises and async await",
        tags: ["JavaScript", "Async", "Promises"],
      },
    ],
    python: [
      {
        title: "Python Tutorial - Python Full Course for Beginners",
        channel: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/_uQrJ0TkZlc/maxresdefault.jpg",
        duration: "6h 14m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
        description: "This Python tutorial for beginners is a complete course that covers Python fundamentals",
        tags: ["Python", "Beginner", "Full Course"],
      },
      {
        title: "Learn Python - Full Course for Beginners",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/rfscVS0vtbw/maxresdefault.jpg",
        duration: "4h 26m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
        description: "This complete Python course teaches programming fundamentals with Python 3",
        tags: ["Python", "Programming", "Basics"],
      },
      {
        title: "Python Crash Course For Beginners",
        channel: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/JJmcL1N2KQs/maxresdefault.jpg",
        duration: "1h 24m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=JJmcL1N2KQs",
        description: "Learn Python basics in this crash course for beginners",
        tags: ["Python", "Crash Course", "Quick Start"],
      },
      {
        title: "Intermediate Python Programming Course",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/HGOBQPFzWKo/maxresdefault.jpg",
        duration: "6h",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=HGOBQPFzWKo",
        description: "Take your Python skills to the next level with this intermediate course",
        tags: ["Python", "Intermediate", "Programming"],
      },
      {
        title: "Python for Data Science - Course for Beginners",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/LHBE6Q9XlzI/maxresdefault.jpg",
        duration: "4h 58m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=LHBE6Q9XlzI",
        description: "Learn Python for data science in this comprehensive course",
        tags: ["Python", "Data Science", "NumPy", "Pandas"],
      },
      {
        title: "Python Django Tutorial for Beginners",
        channel: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/rHux0gMZ3Eg/maxresdefault.jpg",
        duration: "1h 11m",
        level: "Advanced",
        url: "https://www.youtube.com/watch?v=rHux0gMZ3Eg",
        description: "Learn Django web framework with Python in this tutorial for beginners",
        tags: ["Python", "Django", "Web Development"],
      },
    ],
    java: [
      {
        title: "Java Tutorial for Beginners",
        channel: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/eIrMbAQSU34/maxresdefault.jpg",
        duration: "2h 30m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=eIrMbAQSU34",
        description: "Learn Java programming in this comprehensive tutorial for beginners",
        tags: ["Java", "Beginner", "OOP"],
      },
      {
        title: "Learn Java 8 - Full Tutorial for Beginners",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/grEKMHGYyns/maxresdefault.jpg",
        duration: "9h 32m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=grEKMHGYyns",
        description: "This complete Java 8 tutorial covers everything you need to know",
        tags: ["Java", "Java 8", "Full Course"],
      },
      {
        title: "Java Full Course | Java Tutorial for Beginners",
        channel: "Simplilearn",
        thumbnail: "https://i.ytimg.com/vi/CFD9EFcNZTQ/maxresdefault.jpg",
        duration: "12h",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=CFD9EFcNZTQ",
        description: "Learn Java programming from scratch in this full course",
        tags: ["Java", "Tutorial", "Complete Course"],
      },
      {
        title: "Java Collections Framework | Full Course",
        channel: "Amigoscode",
        thumbnail: "https://i.ytimg.com/vi/GdAon80-0KA/maxresdefault.jpg",
        duration: "2h 22m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=GdAon80-0KA",
        description: "Learn the Java Collections Framework in this complete course",
        tags: ["Java", "Collections", "Data Structures"],
      },
      {
        title: "Spring Boot Tutorial for Beginners",
        channel: "Java Guides",
        thumbnail: "https://i.ytimg.com/vi/9SGDpanrc8U/maxresdefault.jpg",
        duration: "2h 30m",
        level: "Advanced",
        url: "https://www.youtube.com/watch?v=9SGDpanrc8U",
        description: "Learn Spring Boot framework for Java in this tutorial for beginners",
        tags: ["Java", "Spring Boot", "Web Development"],
      },
      {
        title: "Java Multithreading",
        channel: "Cave of Programming",
        thumbnail: "https://i.ytimg.com/vi/eQk5AWcTS8w/maxresdefault.jpg",
        duration: "1h 28m",
        level: "Advanced",
        url: "https://www.youtube.com/watch?v=eQk5AWcTS8w",
        description: "Learn multithreading in Java with this comprehensive tutorial",
        tags: ["Java", "Multithreading", "Concurrency"],
      },
    ],
    csharp: [
      {
        title: "C# Tutorial - Full Course for Beginners",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/GhQdlIFylQ8/maxresdefault.jpg",
        duration: "4h 31m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=GhQdlIFylQ8",
        description: "This complete C# tutorial covers all the basics of C# programming",
        tags: ["C#", "Beginner", ".NET"],
      },
      {
        title: "C# Tutorial For Beginners - Learn C# Basics in 1 Hour",
        channel: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/gfkTfcpWqAY/maxresdefault.jpg",
        duration: "1h 2m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=gfkTfcpWqAY",
        description: "Learn C# basics in just one hour with this quick tutorial",
        tags: ["C#", "Quick Start", "Basics"],
      },
      {
        title: "C# Full Course - Learn C# 10 and .NET 6 in 7 hours",
        channel: "Bro Code",
        thumbnail: "https://i.ytimg.com/vi/wxznTygnRfQ/maxresdefault.jpg",
        duration: "7h 16m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=wxznTygnRfQ",
        description: "Learn C# 10 and .NET 6 in this comprehensive course",
        tags: ["C#", ".NET", "Full Course"],
      },
      {
        title: "ASP.NET Core MVC Course (.NET 6)",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/hZ1DASYd9rk/maxresdefault.jpg",
        duration: "8h 30m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=hZ1DASYd9rk",
        description: "Learn ASP.NET Core MVC with .NET 6 in this full course",
        tags: ["C#", "ASP.NET", "Web Development"],
      },
      {
        title: "C# LINQ Tutorial",
        channel: "IAmTimCorey",
        thumbnail: "https://i.ytimg.com/vi/yClSNQdVD7g/maxresdefault.jpg",
        duration: "1h 19m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=yClSNQdVD7g",
        description: "Learn LINQ in C# with this comprehensive tutorial",
        tags: ["C#", "LINQ", "Data Processing"],
      },
      {
        title: "C# Async / Await - Make your app more responsive",
        channel: "IAmTimCorey",
        thumbnail: "https://i.ytimg.com/vi/2moh18sh5p4/maxresdefault.jpg",
        duration: "1h 9m",
        level: "Advanced",
        url: "https://www.youtube.com/watch?v=2moh18sh5p4",
        description: "Learn asynchronous programming in C# with Async and Await",
        tags: ["C#", "Async", "Performance"],
      },
    ],
    react: [
      {
        title: "React JS Crash Course",
        channel: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/w7ejDZ8SWv8/maxresdefault.jpg",
        duration: "1h 48m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=w7ejDZ8SWv8",
        description: "Learn the fundamentals of React in this crash course",
        tags: ["React", "JavaScript", "Frontend"],
      },
      {
        title: "React Tutorial for Beginners",
        channel: "Programming with Mosh",
        thumbnail: "https://i.ytimg.com/vi/Ke90Tje7VS0/maxresdefault.jpg",
        duration: "2h 25m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=Ke90Tje7VS0",
        description: "Learn React fundamentals in this comprehensive tutorial",
        tags: ["React", "Frontend", "Web Development"],
      },
      {
        title: "Full React Course 2020 - Learn Fundamentals, Hooks, Context API, React Router, Custom Hooks",
        channel: "freeCodeCamp.org",
        thumbnail: "https://i.ytimg.com/vi/4UZrsTqkcW4/maxresdefault.jpg",
        duration: "10h 7m",
        level: "Beginner",
        url: "https://www.youtube.com/watch?v=4UZrsTqkcW4",
        description: "Learn React from scratch in this full course",
        tags: ["React", "Hooks", "Context API"],
      },
      {
        title: "React State Management Tutorial with Context API & Hooks",
        channel: "Traversy Media",
        thumbnail: "https://i.ytimg.com/vi/XuFDcZABiDQ/maxresdefault.jpg",
        duration: "37m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=XuFDcZABiDQ",
        description: "Learn state management in React using Context API and Hooks",
        tags: ["React", "State Management", "Context API"],
      },
      {
        title: "React Redux Tutorial",
        channel: "Codevolution",
        thumbnail: "https://i.ytimg.com/vi/9boMnm5X9ak/maxresdefault.jpg",
        duration: "2h 39m",
        level: "Intermediate",
        url: "https://www.youtube.com/watch?v=9boMnm5X9ak",
        description: "Learn Redux state management with React in this tutorial",
        tags: ["React", "Redux", "State Management"],
      },
      {
        title: "React Testing Library Tutorial",
        channel: "The Net Ninja",
        thumbnail: "https://i.ytimg.com/vi/7dTTFW7yACQ/maxresdefault.jpg",
        duration: "2h 4m",
        level: "Advanced",
        url: "https://www.youtube.com/watch?v=7dTTFW7yACQ",
        description: "Learn how to test React applications using React Testing Library",
        tags: ["React", "Testing", "Jest"],
      },
    ],
  }

  // Default to JavaScript if language not found
  const videos = videoData[language as keyof typeof videoData] || videoData.javascript

  return <VideoPageClient language={language} videos={videos} />
}
